parameter_defaults:
  ContainerCinderVolumeImage: <registry_host>:8787/rhosp-rhel8/openstack-cinder-volume-datacore:latest
  CinderEnableIscsiBackend: false
  Debug: true
  ControllerExtraConfig:
    cinder::config::cinder_config:
      datacore/volume_driver:
        value: cinder.volume.drivers.datacore.iscsi.ISCSIVolumeDriver
      datacore/san_ip:
        value: <sansymphony_management_ip_addr>
      datacore/san_login:
        value: <username>
      datacore/san_password:
        value: <password>
      datacore/volume_backend_name:
        value: datacore_iscsi
      datacore/datacore_disk_type:
        value: single
      datacore/datacore_disk_pools:
        value: <diskpoolname>
      datacore/datacore_api_timeout:
        value: 300
    cinder_user_enabled_backends: ['datacore']
